FROM ibisba/rpsbml

WORKDIR /home/

RUN conda install -y -c rdkit rdkit && \
    pip install --no-cache-dir cobra && \
    pip install --no-cache-dir scipy && \
    wget https://github.com/Galaxy-SynBioCAD/rpRanker_image/blob/master/rpCache.py && \
    wget https://github.com/Galaxy-SynBioCAD/rpRanker_image/blob/master/rpFBA.py && \
    wget https://github.com/Galaxy-SynBioCAD/rpRanker_image/blob/master/rpFBAServe.py && \
 
ENTRYPOINT ["python"]
CMD ["/home/rpFBAServe.py"]

# Open server port
EXPOSE 8994
